version: "3"
services:
  web-service:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:80
    secrets:
      - MYSQL_PASSWORD
    command: ["npx", "nodemon", "app.js", "-L"]
    
  mysql:
    image: mysql:8.0.35
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user_biblioteca
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
volumes:
  mysql_data:
secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./.secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_PASSWORD:
    file: ./.secrets/MYSQL_PASSWORD.txt
